#!/usr/bin/python3
import sys

def factorize(n):
    factors = []
    for i in range(2, n):
        if n % i == 0:
            factors.append((i, n//i))
    return factors

if len(sys.argv) != 2:
    exit()

with open(sys.argv[1], "r") as f:
    for line in f:
        n = int(line.strip())
        factor_pairs = factorize(n)
        for p, q in factor_pairs:
            print("{:.0f}={:.0f}*{:.0f}".format(n, p, q))
