#!/usr/bin/python3
"""
Module that factorize numbers
"""
import sys


def factorize(value):
    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    i = 2
    while value % i:
        i += 1

    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
    print(value, "<- value-aft")
    print()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit()

    try:
        with open(sys.argv[1]) as file:
            line = file.readline()

            while line:
                value = int(line.split('\n')[0])
                factorize(value)
                line = file.readline()
    except Exception as e:
        pass
